import { PGlite } from '@electric-sql/pglite';
import { readFileSync } from 'node:fs';
export async function database() {
 const db=new PGlite();
 await db.exec(`
 create role anon; create role authenticated; create role service_role bypassrls;
 create table hockey_equipment_items(id bigint generated by default as identity primary key,item_code text unique not null,category text not null,category_label text not null,brand text not null,size text not null,image text,condition_note text,status text not null default 'verfügbar' check(status in ('verfügbar','verliehen')),is_deleted boolean default false,created_at timestamptz default now());
 create table hockey_rentals(id bigint generated by default as identity primary key,renter_name text not null,rented_at date not null default current_date,due_date date,returned_at date,paid boolean default false,fee_total numeric default 0 check(fee_total>=0),note text,rental_type text default 'single',created_at timestamptz default now(),check(returned_at is null or returned_at>=rented_at));
 create table hockey_rental_items(id bigint generated by default as identity primary key,rental_id bigint references hockey_rentals(id) on delete cascade,item_id bigint references hockey_equipment_items(id),added_at date default current_date,returned_at date,exchange_note text,created_at timestamptz default now());
 create unique index idx_hockey_rental_items_active_item_global on hockey_rental_items(item_id) where returned_at is null;
 `);
 await db.exec(readFileSync('supabase_migration_contracts.sql','utf8'));
 await db.exec(`alter table hockey_rental_contracts add column contract_snapshot jsonb,add column contract_version text,add column pdf_path text,add column signing_token_hash text,add column signing_token_expires_at timestamptz;`);
 await db.exec(readFileSync('supabase/migrations/20261006075151_integrity_and_contracts.sql','utf8'));
 return db;
}
export async function mutate(db:PGlite,action:string,data:any) {
 return (await db.query<{result:any}>('select hockey_mutate_rental($1,$2::jsonb) result',[action,JSON.stringify(data)])).rows[0].result;
}
export async function contract(db:PGlite,action:string,id:number,data:any={},token:string|null=null,hash:string|null=null,template:any={sections:[]}) {
 return (await db.query<{result:any}>('select hockey_contract_write($1,$2,$3::jsonb,$4,$5,$6::jsonb) result',[action,id,JSON.stringify(data),token,hash,JSON.stringify(template)])).rows[0].result;
}
export const fields={first_name:'Test',last_name:'Person',child_name:'Kind',street:'Testweg',house_number:'1',postal_code:'12345',city:'Teststadt',phone:'0123456789',email:'test@example.com',iban:'DE89370400440532013000',fee_amount:60,deposit_amount:50};
export async function seed(db:PGlite) {
 for(let i=1;i<=4;i++) await mutate(db,'create_item',{prefix:'H',category:'Helm',category_label:'Helm',brand:'Test',size:'S'});
 return await mutate(db,'create',{renter_name:'Test',item_ids:[1,2],fee_total:60,rented_at:'2026-01-31'});
}
