begin;

create table public.hockey_contract_deliveries (
 id bigint generated by default as identity primary key,
 contract_id bigint not null references public.hockey_rental_contracts(id),
 rental_id bigint not null references public.hockey_rentals(id),
 recipient text not null,
 recipient_role text not null check(recipient_role in ('renter','club')),
 pdf_path text not null,
 pdf_sha256 text,
 status text not null default 'pending' check(status in ('pending','sending','sent','failed','uncertain')),
 attempts integer not null default 0,
 attempt_token uuid,
 provider text,
 provider_message_id text,
 last_error text,
 claimed_at timestamptz,
 sent_at timestamptz,
 created_at timestamptz not null default now(),
 unique(contract_id,recipient)
);
create index hockey_contract_deliveries_rental on public.hockey_contract_deliveries(rental_id);
alter table public.hockey_contract_deliveries enable row level security;
revoke all on public.hockey_contract_deliveries from public,anon,authenticated;
grant select,insert,update on public.hockey_contract_deliveries to service_role;
revoke all on sequence public.hockey_contract_deliveries_id_seq from public,anon,authenticated;
grant usage,select on sequence public.hockey_contract_deliveries_id_seq to service_role;

create function public.hockey_contract_mail(p_action text,p_rental bigint,p_job bigint default null,
 p_token uuid default null,p_data jsonb default '{}'::jsonb)
returns jsonb language plpgsql security invoker set search_path=public,pg_temp as $$
declare v_contract public.hockey_rental_contracts; v_job public.hockey_contract_deliveries; v_result jsonb;
begin
 if p_action='enqueue' then
  select * into v_contract from public.hockey_rental_contracts where rental_id=p_rental;
  if not found or v_contract.status<>'signed' then raise exception 'Nur unterschriebene Verträge können versendet werden'; end if;
  if v_contract.pdf_path is null then raise exception 'Archiviertes PDF fehlt'; end if;
  if v_contract.email is null or btrim(v_contract.email) !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then
   raise exception 'E-Mail-Adresse im Vertrag fehlt';
  end if;
  insert into public.hockey_contract_deliveries(contract_id,rental_id,recipient,recipient_role,pdf_path,pdf_sha256)
  values(v_contract.id,p_rental,lower(btrim(v_contract.email)),'renter',v_contract.pdf_path,v_contract.pdf_sha256),
   (v_contract.id,p_rental,'foerderverein-wieselarpke@mail.de','club',v_contract.pdf_path,v_contract.pdf_sha256)
  on conflict(contract_id,recipient) do nothing;
 elsif p_action='claim' then
  if p_token is null then raise exception 'Versuchstoken fehlt'; end if;
  update public.hockey_contract_deliveries set status='sending',attempt_token=p_token,
   attempts=attempts+1,claimed_at=clock_timestamp(),last_error=null,provider=p_data->>'provider'
  where id=p_job and rental_id=p_rental and status in ('pending','failed') returning * into v_job;
  return case when found then to_jsonb(v_job) else null end;
 elsif p_action='finish' then
  if p_token is null or (p_data->>'status') not in ('sent','failed','uncertain') or p_data->>'status' is null then
   raise exception 'Ungültiges Versandergebnis';
  end if;
  update public.hockey_contract_deliveries set status=p_data->>'status',
   provider_message_id=left(p_data->>'message_id',500),last_error=left(p_data->>'error',500),
   sent_at=case when p_data->>'status'='sent' then clock_timestamp() else null end
  where id=p_job and rental_id=p_rental and status='sending' and attempt_token=p_token;
  if not found then raise exception 'Versandversuch ist nicht mehr aktuell'; end if;
 elsif p_action<>'status' then raise exception 'Unbekannte Versandaktion';
 end if;
 select coalesce(jsonb_agg(jsonb_build_object('id',id,'recipient',recipient,'recipient_role',recipient_role,
  'status',case when status='sending' and claimed_at<clock_timestamp()-interval '3 minutes' then 'uncertain' else status end,
  'attempts',attempts,'sent_at',sent_at,'last_error',last_error) order by id),'[]'::jsonb)
 into v_result from public.hockey_contract_deliveries where rental_id=p_rental;
 return v_result;
end $$;

-- Queue creation shares the signature transaction; no emails are sent in SQL.
-- Existing signed contracts are deliberately not queued by this migration.
create function public.hockey_enqueue_signed_contract_mail()
returns trigger language plpgsql security invoker set search_path=public,pg_temp as $$
begin
 perform public.hockey_contract_mail('enqueue',new.rental_id);
 return new;
end $$;
create trigger hockey_enqueue_signed_contract_mail after update of status on public.hockey_rental_contracts
for each row when (old.status is distinct from 'signed' and new.status='signed')
execute function public.hockey_enqueue_signed_contract_mail();

revoke all on function public.hockey_contract_mail(text,bigint,bigint,uuid,jsonb),
 public.hockey_enqueue_signed_contract_mail() from public,anon,authenticated;
grant execute on function public.hockey_contract_mail(text,bigint,bigint,uuid,jsonb),
 public.hockey_enqueue_signed_contract_mail() to service_role;

commit;
